-- SMARTCOFFEE BASE DE DADOS - DML
-- EXECUTE SEMPRE QUE QUISE RESTAURAR A AULA

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_BRUNO;

CREATE DATABASE SMARTCOFFEE_DML_BRUNO;

USE SMARTCOFFEE_DML_BRUNO;
CREATE TABLE CLIENTE (
ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (100)NOT NULL,
EMAIL VARCHAR (120) UNIQUE,
TELEFONE VARCHAR (15),
CIDADE VARCHAR (60) NOT NULL,
ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR (60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR (100) NOT NULL,
PRECO DECIMAL (10,2) NOT NULL,
ATIVO BOOLEAN NOT NULL,
ID_CATEGORIA INT NOT NULL,
CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
REFERENCES CATEGORIA     (ID_CATEGORIA) 
);

CREATE TABLE PEDIDO (
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
DATA_PEDIDO DATETIME NOT NULL,
STATUS_PEDIDO ENUM('ABERTO','PREPARANDO','FINALIZADO','CANCELADO') NOT NULL,
VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ID_CLIENTE INT NOT NULL,
CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
ID_ITEM INT NOT NULL,
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRECO_UNIVERSITARIO DECIMAL (10,2) NOT NULL,
OBSERVACAO VARCHAR (150),
CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)

);

CREATE TABLE FORMA_PAGAMENTO (
ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR (40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_FORMA_PAGAMENTO INT NOT NULL,
VALOR DECIMAL (10,2) NOT NULL,
DATA_PAGAMENTO DATETIME,
CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

-- INSERCAO DE DADOS
