-- SMARTCOFFEE BASE DE DADOS - DML
-- EXECUTE SEMPRE QUE QUISER RESTAURAR A AULA

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_BRUNO;

CREATE DATABASE SMARTCOFFEE_DML_BRUNO;

USE SMARTCOFFEE_DML_BRUNO;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (120) UNIQUE,
    TELEFONE VARCHAR (15),
    CIDADE VARCHAR (60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR (60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR (100) NOT NULL,
    PRECO DECIMAL (10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('ABERTO','PREPARANDO','FINALIZADO','CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL (10,2) NOT NULL,
    OBSERVACAO VARCHAR (150),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR (40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL (10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

-- INSERÇÃO DE DADOS
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO, DATA_CADASTRO) VALUES 
('ANA SILVA','ANA@EMAIL.COM','19999999999','LIMEIRA-SP',TRUE, NULL),
('BRUNO SOUZA','BRUNO@EMAIL.COM','19999999998','RIO CLARO-SP',TRUE, NULL),
('CARLOS PEREIRA','CARLOS@EMAIL.COM','19999999997','LIMEIRA-SP',TRUE, NULL),
('DANIELA COSTA','DANIELA@EMAIL.COM','19999999996','AMERICANA-SP',TRUE, NULL),
('ELIAS MORAES','ELIAS@EMAIL.COM','19999999995','LIMEIRA-SP',TRUE, NULL),
('FELIPE ALMEIDA','FELIPE@EMAIL.COM','19999999994','LIMEIRA-SP',TRUE, NULL),
('GABRIEL LIMA','GABRIEL@EMAIL.COM','19999999993','IRACEMAPOLIS-SP',TRUE, NULL),
('HUGO MARTINS','HUGO@EMAIL.COM','19999999990','CORDEIRÓPOLIS-SP',TRUE, NULL);

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES
('CAFÉ'),
('BEBIDAS QUENTES'),
('BEBIDAS GELADAS'),
('SOBREMESAS'),
('LANCHES'),
('SANDUICHES'),
('SALGADOS'),
('DOCES');

INSERT INTO PRODUTO (NOME_PRODUTO, PRECO, ATIVO, ID_CATEGORIA) VALUES
('EXPRESSO', 5.00, TRUE, 1),
('CAPPUCCINO', 7.50, TRUE, 2),
('LATTE', 6.50, TRUE, 2),
('MOCHA', 8.00, TRUE, 2),
('CHOCOLATE QUENTE', 4.50, TRUE, 2),
('CHA VERDE', 3.00, TRUE, 2),
('REFRIGERANTE', 4.00, TRUE, 3),
('SUCO NATURAL', 5.50, TRUE, 3),
('AGUA MINERAL', 2.50, TRUE, 3),
('TORTA DE LIMAO', 6.00, TRUE, 4),
('BOLO DE CHOCOLATE', 5.50, TRUE, 4),
('PASTEL DE CARNE', 4.00, TRUE, 5),
('SANDUICHE NATURAL', 7.00, TRUE, 6),
('CROISSANT', 3.50, TRUE, 7),
('BRIGADEIRO', 2.00, TRUE, 8);

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
('2024-06-01 10:00:00','ABERTO', 0.00, 1),
('2024-06-01 11:30:00','PREPARANDO', 0.00, 2),
('2024-06-01 12:15:00','FINALIZADO', 0.00, 3),
('2024-06-01 13:45:00','CANCELADO', 0.00, 4),
('2024-06-02 09:20:00','ABERTO', 0.00, 5),
('2024-06-02 10:50:00','PREPARANDO', 0.00, 6),
('2024-06-02 11:30:00','FINALIZADO', 0.00, 7),
('2024-06-02 12:45:00','CANCELADO', 0.00, 8),
(NOW(), 'ABERTO', 0.00, 8);

SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(1, 1, 2, 5.00, 'sem açucar'),
(1, 10, 1, 6.00, NULL),
(2, 2, 1, 7.50, 'com canela'),
(2, 11, 2, 5.50, NULL),
(3, 3, 1, 6.50, NULL),
(3, 12, 3, 4.00, 'bem passado'),
(4, 4, 2, 8.00, NULL),
(4, 13, 1, 7.00, 'sem maionese'),
(5, 5, 1, 4.50, NULL),
(5, 14, 2, 3.50, NULL),
(6, 6, 3, 3.00, 'com mel'),
(6, 15, 4, 2.00, NULL);

INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES 
('DINHEIRO'),
('DEBITO'),
('CREDITO'),
('PIX');

INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(3, 2, 20.00, '2024-06-01 12:30:00'),
(6, 1, 15.00, '2024-06-02 11:00:00'),
(7, 3, 25.00, '2024-06-02 12:00:00'),
(6, 4, 10.00, NOW()),
(8, 4, 10.00, '2024-06-02 13:00:00'),
(9, 4, 10.00, NOW());

-- UPDATE OU ATUALIZACOES DE DADOS

UPDATE CLIENTE 
SET TELEFONE = '19999999999'
WHERE ID_CLIENTE = 3;
-- DETERMINAR O COMANDO WHERE SEMPRE

UPDATE PRODUTO
SET PRECO = PRECO * 1.05
WHERE ID_CATEGORIA = 1;

-- ATUALIZANDO SEM WHERE
-- UPDATE PRODUTO
-- SET PRECO = 1.00
-- CUIDADO AO UTILIZAR ESSE COMANDO DA TABELA, MUDA TODOS PARA UM NUMERO SO

-- ATUALIZZANDO CONDICIONAIS
UPDATE PRODUTO 
SET PRECO = CASE 
    WHEN PRECO < 10 THEN PRECO * 1.10
    ELSE PRECO * 1.05
END
WHERE ATIVO = TRUE;

-- ATUALIZANDO PARA NULL
UPDATE CLIENTE
SET TELEFONE = NULL
WHERE ID_CLIENTE = 5;


-- MODIFICACAO E ATUALIZACAO
-- EXCLUIR REGISTROS OU DADOS
DELETE FROM CLIENTE
WHERE ID_CLIENTE = 2;

-- LIMPA TABELA OU REMOVE TODOS OS REGISTROS
TRUNCATE TABLE CLIENTE

-- EXCLUIR REGISTROS COM ESTRUTURA LOGICA
UPDATE PRODUTO
SET ATIVO = FALSE
WHERE ID_PRODUTO = 10;

UPDATE CLIENTE
SET ATIVO = FALSE
WHERE ID_CLIENTE = 5;


-- CONSULTAR INFORMACOES NO BCD
SELECT * FROM CLIENTE;

-- CONSULTAR POR ID
SELECT * FROM PRODUTO
ID_CATEGORIA = 1;






-- MENSAGEM DE SUCESSO
SELECT 'BANCO DE DADOS SMARTCOFFEE_DML_BRUNO CRIADO COM SUCESSO!' AS mensagem;


